/**
 * Non-English RAG section content. English is generated from docs/PLATFORM_KB.md.
 * Update these when you change platform rules; keep aligned with PLATFORM_KB.md meaning.
 */

export type KbLocale = 'en' | 'it' | 'fr' | 'de';

export type LocaleSectionMap = Record<string, Record<Exclude<KbLocale, 'en'>, string>>;

export const HELP_KB_LOCALE_SECTIONS: LocaleSectionMap = {
  account_and_biography_model: {
    it: `Ogni account gestisce una sola biografia: autobiografia o memorial (scelta irreversibile alla creazione). Non si può aggiungere una seconda biografia. Autobiografia + memorial del padre: due account con email diverse. Memorial per più familiari: un account per persona. Due prospettive sullo stesso defunto: account separati. Creazione solo da /onboarding. Dubbi: https://biographylibrary.org/contacts`,
    fr: `Chaque compte gère une seule biographie : autobiographie ou mémorial (choix irréversible à la création). Impossible d'ajouter une seconde biographie. Autobiographie + mémorial : deux comptes avec e-mails différents. Plusieurs mémoriaux : un compte par personne. Perspectives multiples sur un défunt : comptes séparés. Création via /onboarding. Questions : https://biographylibrary.org/contacts`,
    de: `Jedes Konto verwaltet genau eine Biografie: Autobiografie oder Gedenkbuch (unwiderrufliche Wahl bei Erstellung). Keine zweite Biografie möglich. Eigene Autobiografie + Gedenkbuch: zwei Konten mit verschiedenen E-Mails. Mehrere Gedenkbücher: ein Konto pro Person. Verschiedene Perspektiven auf dieselbe Person: separate Konten. Erstellung nur über /onboarding. Fragen: https://biographylibrary.org/contacts`,
  },
  platform_intro: {
    it: `Biography Library è un archivio digitale permanente, open source e senza scopo di lucro, ospitato in Svizzera. Gli utenti scrivono autobiografie o biografie di familiari diretti deceduti. Non è un social network né un business di dati commerciali. L'assistente Aiuto spiega come funziona la piattaforma con linguaggio chiaro e semplice. Non fornisce consulenza legale, medica, fiscale o psicologica. In caso di dubbio, indirizza a https://biographylibrary.org/contacts.`,
    fr: `Biography Library est une archive numérique permanente, open source et à but non lucratif, hébergée en Suisse. Les utilisateurs écrivent des autobiographies ou des biographies de membres directs de la famille décédés. Ce n'est pas un réseau social ni une entreprise commerciale de données. L'assistant Aide explique le fonctionnement de la plateforme en langage clair et simple. Il ne fournit pas de conseils juridiques, médicaux, fiscaux ou psychologiques. En cas de doute, orientez vers https://biographylibrary.org/contacts.`,
    de: `Biography Library ist ein dauerhaftes, quelloffenes, gemeinnütziges digitales Archiv in der Schweiz. Nutzer schreiben Autobiografien oder Biografien verstorbener direkter Familienmitglieder. Es ist kein soziales Netzwerk und kein kommerzielles Datengeschäft. Der Hilfe-Assistent erklärt die Plattform in klarer, einfacher Sprache. Er gibt keine Rechts-, Medizin-, Steuer- oder Psychologieberatung. Bei Unsicherheit verweisen Sie auf https://biographylibrary.org/contacts.`,
  },
  manifesto: {
    it: `Principi chiave: (1) Ogni vita merita memoria. (2) Solo la propria autobiografia o la biografia di un familiare diretto deceduto. (3) Open source AGPL v3. (4) Solo IA open source etica su infrastruttura svizzera; l'IA aiuta a scrivere, non sostituisce la voce; disattivabile. (5) Identità dichiarata in registrazione, 18+. (6) Privacy: visibilità pubblica, solo link, solo famiglia o privata; dati mai venduti. (7) Moderazione rigorosa per contenuti illegali/dannosi. (8) Niente pubblicità o vendita dati. (9) Impegno alla conservazione a lungo termine. (10) Governance associazione non profit a Lugano.`,
    fr: `Principes clés : (1) Chaque vie mérite d'être mémorisée. (2) Seulement votre autobiographie ou celle d'un membre direct de la famille décédé. (3) Open source AGPL v3. (4) IA open source éthique hébergée en Suisse uniquement ; l'IA aide à écrire, ne remplace pas la voix ; désactivable. (5) Identité déclarée à l'inscription, 18+. (6) Confidentialité : public, lien seul, famille seule ou privé ; données jamais vendues. (7) Modération stricte des contenus illégaux/nocifs. (8) Pas de publicité ni vente de données. (9) Engagement de préservation à long terme. (10) Gouvernance association à but non lucratif à Lugano.`,
    de: `Kernprinzipien: (1) Jedes Leben verdient Erinnerung. (2) Nur eigene Autobiografie oder Biografie eines verstorbenen direkten Familienmitglieds. (3) Open Source AGPL v3. (4) Nur ethische Open-Source-KI in der Schweiz; KI hilft beim Schreiben, ersetzt nicht die Stimme; abschaltbar. (5) Identität bei Registrierung, 18+. (6) Datenschutz: öffentlich, nur Link, nur Familie oder privat; Daten werden nie verkauft. (7) Strenge Moderation illegaler/schädlicher Inhalte. (8) Keine Werbung oder Datenverkauf. (9) Langfristige Bewahrung. (10) Gemeinnütziger Verein in Lugano.`,
  },
  registration_and_onboarding: {
    it: `Registrazione: nome, cognome, email, password. Minimo 18 anni. I nuovi account entrano in lista d’attesa: la home / è la landing; l’accesso è su /login. Dopo la conferma email vedi solo la data di registrazione, mai il numero in coda. Quando lo staff dà l’accesso, completa il wizard su /onboarding (non dal pannello) per creare l’unica biografia: tipo (autobiografia o memorial), dichiarazioni legali, titolo o nomi protagonista/scrittore e visibilità. Non si sceglie tra capitoli guidati, importazione o testo già pronto: si arriva su un foglio vuoto. Il pannello mostra solo la biografia esistente. Catalogo e risolutore UM restano pubblici.`,
    fr: `Inscription : prénom, nom, e-mail, mot de passe. 18 ans minimum. Les nouveaux comptes rejoignent une liste d’attente : l’accueil / est la landing ; la connexion est sur /login. Après confirmation de l’e-mail, seule la date d’inscription s’affiche, jamais le numéro de file. Quand l’équipe accorde l’accès, complétez l’assistant sur /onboarding (pas le tableau de bord) pour créer votre unique biographie : type, déclarations légales, titre ou noms et visibilité. On ne choisit plus entre chapitres guidés, import ou texte déjà prêt : on arrive sur une page vide. Le tableau de bord affiche seulement la biographie existante. Catalogue et résolveur UM restent publics.`,
    de: `Registrierung: Vorname, Nachname, E-Mail, Passwort. Mindestens 18 Jahre. Neue Konten kommen auf die Warteliste: Startseite / ist die Landing; Anmeldung unter /login. Nach E-Mail-Bestätigung sehen Sie nur das Anmeldedatum, nie die Wartenummer. Wenn das Team Zugang gibt, den Assistenten unter /onboarding abschließen (nicht Dashboard), um die eine Biografie zu erstellen: Typ, Rechtserklärungen, Titel oder Namen und Sichtbarkeit. Es gibt keine Wahl zwischen geführten Kapiteln, Import oder fertigem Text: man kommt auf ein leeres Blatt. Das Dashboard zeigt nur die bestehende Biografie. Katalog und UM-Resolver bleiben öffentlich.`,
  },
  writing_modes: {
    it: `Un solo foglio, come un programma di scrittura. Non ci sono capitoli di vita già scritti e non c’è una modalità testo libero. I capitoli sono i titoli che l’autore segna. Se il testo non ha titoli, resta intero: i capitoli si aggiungono dopo, non si inventano. Echo può proporre un ordine, per esempio cronologico, e deve lasciare spazio alle riflessioni, non a un elenco di fatti. In privato può ricordare i grandi temi di una vita solo per fare una domanda se manca qualcosa. Quei temi non diventano capitoli vuoti.`,
    fr: `Une seule page, comme un traitement de texte. Il n’y a pas de chapitres de vie déjà écrits ni de mode texte libre. Les chapitres sont les titres que l’auteur marque. Sans titres, le texte reste entier : les chapitres s’ajoutent ensuite, on ne les invente pas. Echo peut proposer un ordre, par exemple chronologique, et doit laisser de la place à la réflexion, pas à une liste de faits. En privé, Echo peut se souvenir des grands thèmes d’une vie seulement pour poser une question si quelque chose manque. Ces thèmes ne deviennent pas des chapitres vides.`,
    de: `Ein einziges Blatt, wie ein Schreibprogramm. Es gibt keine schon geschriebenen Lebenskapitel und keinen Freitextmodus. Kapitel sind die Titel, die die Autorin oder der Autor setzt. Ohne Titel bleibt der Text ganz: Kapitel kommen später dazu, sie werden nicht erfunden. Echo darf eine Form vorschlagen, zum Beispiel chronologisch, und muss Raum für Nachdenken lassen, nicht für eine Faktenliste. Intern darf Echo die großen Lebensthemen nur nutzen, um eine Frage zu stellen, wenn etwas fehlt. Diese Themen werden keine leeren Kapitel.`,
  },
  ai_tools: {
    it: `Gli strumenti IA stanno nella barra di formattazione, non in una barra in alto: grammatica, aiuto, riassunto, revisione. Il contatore d’uso è in quella stessa barra, sopra il conteggio dei caratteri, alto come i pulsanti. Limiti giornalieri (40) e settimanali (200); azioni pesanti valgono 2. Reset a mezzanotte UTC e il lunedì UTC. L'IA non inventa fatti né pubblica da sola.`,
    fr: `Les outils IA sont dans la barre de mise en forme, pas dans une barre du haut : grammaire, aide, résumé, révision. Le compteur d'usage est dans cette même barre, au-dessus du nombre de caractères, à la hauteur des boutons. Limites journalières (40) et hebdomadaires (200) ; actions lourdes = 2. Réinitialisation minuit UTC et lundi UTC. L'IA n'invente pas de faits et ne publie pas seule.`,
    de: `Die KI-Werkzeuge liegen in der Formatierungsleiste, nicht in einer oberen Leiste: Grammatik, Hilfe, Zusammenfassung, Überprüfung. Der Nutzungszähler steht in derselben Leiste, über der Zeichenzahl, so hoch wie die Schaltflächen. Tageslimit 40, Wochenlimit 200; schwere Aktionen zählen 2. Reset Mitternacht UTC und Montag UTC. Die KI erfindet keine Fakten und veröffentlicht nicht von allein.`,
  },
  conversation_mode: {
    it: `Non esiste una modalità conversazione separata. La biografia è un solo foglio, sempre modificabile. Echo sta sotto: striscia nera «Echo - il tuo assistente alla scrittura», aperta di default. Chiuderla nasconde chat, campo e icone. Una bozza entra nel foglio solo se la accetti. La chat non viene copiata. Le conversazioni vecchie restano e si aprono con Conversazioni precedenti. Non c’è un pulsante flottante.`,
    fr: `Il n'y a pas de mode conversation séparé. La biographie est une seule page, toujours modifiable. Echo est dessous : bande noire « Echo — votre assistant à l'écriture », ouverte par défaut. La fermer cache la conversation, le champ et les icônes. Un brouillon n'entre dans la page que si vous l'acceptez. La conversation n'est pas copiée. Les anciens échanges restent et s'ouvrent avec Conversations précédentes. Il n'y a pas de bouton flottant.`,
    de: `Es gibt keinen separaten Konversationsmodus. Die Biografie ist eine einzige Seite und immer bearbeitbar. Echo steht darunter: schwarzer Streifen «Echo — dein Schreibassistent», standardmäßig offen. Schließen blendet Chat, Feld und Symbole aus. Ein Entwurf kommt nur auf die Seite, wenn Sie ihn annehmen. Der Chat wird nicht kopiert. Ältere Gespräche bleiben und öffnen sich über Frühere Gespräche. Es gibt keine schwebende Schaltfläche.`,
  },
  book_structure_photos: {
    it: `Pannello Struttura libro (barra laterale): frontespizio opzionale (Dedica, Epigrafe, Prefazione) e fine libro (Epilogo, Ringraziamenti, Crediti) per PDF. Note e To-Do: blocco note privato, non esportato. Foto: JPG/PNG/WEBP fino 5 MB, max 30 in galleria, didascalie, riordino trascinando; incluse nel lettore online e galleria PDF dopo l'ultimo capitolo.`,
    fr: `Panneau Structure du livre : avant-propos optionnel (Dédicace, Épigraphe, Préface) et fin (Épilogue, Remerciements, Crédits) pour le PDF. Notes & To-Do : bloc-notes privé, non exporté. Photos : JPG/PNG/WEBP jusqu'à 5 Mo, max 30 en galerie, légendes, réordonner par glisser-déposer ; incluses dans le lecteur et la galerie PDF après le dernier chapitre.`,
    de: `Buchstruktur-Panel: optionales Vorspann (Widmung, Epigraph, Vorwort) und Nachspann (Epilog, Danksagungen, Credits) für PDF. Notizen & To-Do: privates Notizbuch, nicht exportiert. Fotos: JPG/PNG/WEBP bis 5 MB, max. 30 Galerie-Fotos, Bildunterschriften, per Drag & Drop sortieren; im Online-Leser und PDF-Galerie nach dem letzten Kapitel.`,
  },
  import_export: {
    it: `Importa testo è sempre visibile, subito prima di Esporta. Si incolla o si carica .txt, .rtf o .docx sul foglio. Si accetta anche un PDF digitale il cui testo si può selezionare, fino a 30 MB. Prima si chiede se tenere la copertina originale. Se sì, quella immagine è la prima pagina del PDF generato. Se la forma è diversa dalla pagina del libro (176×250 mm), non si stira: resta al centro con un bordo beige, lo stesso colore della quarta di copertina. Se la forma coincide già, riempie la pagina. Grassetto, corsivo e titoli restano solo se il carattere del PDF li registra ancora. I titoli diventano capitoli nell'elenco. Un testo senza titoli resta intero. L'interno viene ricomposto come testo, non come foto delle pagine. Se il PDF è solo una fotografia o una scansione, si dice chiaramente, senza promettere di riconoscere la scrittura. Se c'è già del testo, una domanda chiede se sostituirlo o aggiungere il nuovo in fondo. Niente è già scelto. Importa testo è sempre visibile, subito prima di Esporta. Esporta è PDF, Word e testo di tutto il foglio. PDF B5 con copertina e galleria foto opzionale. Il file esportato è tuo.`,
    fr: `Importer du texte est toujours visible, juste avant Exporter. On colle ou téléverse .txt, .rtf ou .docx sur la page. Un PDF numérique dont le texte se sélectionne est aussi accepté, jusqu'à 30 Mo. On demande d'abord s'il faut garder la couverture originale. Si oui, cette image est la première page du PDF généré. Si la forme diffère de la page du livre (176×250 mm), on ne l'étire pas : elle reste au centre avec une bordure beige, la même couleur que la quatrième de couverture. Si la forme correspond déjà, elle remplit la page. Gras, italique et titres restent seulement si la police du PDF les enregistre encore. Les titres deviennent des chapitres. Un texte sans titres reste entier. L'intérieur est recomposé en texte, pas en photo des pages. Si le PDF n'est qu'une photo ou un scan, on le dit clairement, sans promettre de reconnaître l'écriture. S'il y a déjà du texte, une question demande de le remplacer ou d'ajouter le nouveau à la fin. Rien n'est choisi d'avance. Importer du texte est toujours visible, juste avant Exporter. L'export est PDF, Word et texte de toute la page. Le fichier exporté vous appartient.`,
    de: `Text importieren ist immer sichtbar, direkt vor Exportieren. .txt, .rtf oder .docx werden auf die Seite eingefügt oder hochgeladen. Ein digitales PDF, dessen Text sich auswählen lässt, wird ebenfalls angenommen, bis 30 MB. Zuerst wird gefragt, ob das Originalcover behalten werden soll. Wenn ja, ist dieses Bild Seite 1 des erzeugten PDF. Weicht die Form von der Buchseite ab (176×250 mm), wird es nicht gestreckt: es bleibt mittig mit einem beigen Rand, derselben Farbe wie die Rückseite. Passt die Form schon, füllt es die Seite. Fett, Kursiv und Titel bleiben nur, wenn die PDF-Schrift sie noch verzeichnet. Überschriften werden Kapitel. Text ohne Überschriften bleibt ganz. Der Innenteil wird neu als Text gesetzt, nicht als Foto der Seiten. Ist das PDF nur ein Foto oder ein Scan, wird das klar gesagt, ohne Schrifterkennung zu versprechen. Ist schon Text da, erscheint die Frage, ob er ersetzt oder der neue Text unten angefügt wird. Nichts ist vorausgewählt. Text importieren ist immer sichtbar, direkt vor Exportieren. Export ist PDF, Word und Text der ganzen Seite. Die exportierte Datei gehört Ihnen.`,
  },
  rights_chapters: {
    it: `L'autore mantiene il copyright; la piattaforma è solo custode. Nessun addestramento IA commerciale su biografie private/semi-private/famiglia. Capitoli autobiografia: dopo la prima pubblicazione, nuovo capitolo dopo minimo 365 giorni; capitoli pubblicati immutabili. Dopo la morte dell'autore, autobiografia congelata; la famiglia può scrivere biografie separate collegate con account propri. Biografie di deceduti: solo familiari diretti. Vedi memorial_review_window: 30 giorni con la data provisional_until, non uno stato provisional. La segnalazione resta possibile per sempre.`,
    fr: `L'auteur conserve le copyright ; la plateforme est gardienne uniquement. Pas d'entraînement IA commercial sur biographies privées/semi-privées/famille. Chapitres autobiographie : après première publication, nouveau chapitre après 365 jours minimum ; chapitres publiés immuables. Après le décès de l'auteur, autobiographie figée ; la famille peut écrire des biographies séparées liées avec leurs propres comptes. Biographies de décédés : famille directe seulement ; 30 jours de révision temporaire après publication. Après ces 30 jours, un signalement reste possible pour toujours.`,
    de: `Autor behält Urheberrecht; Plattform nur Verwahrer. Kein kommerzielles KI-Training bei privaten/semi-privaten/Familien-Biografien. Autobiografie-Kapitel: nach erster Veröffentlichung neues Kapitel frühestens nach 365 Tagen; veröffentlichte Kapitel unveränderlich. Nach Tod des Autors eingefroren; Familie kann separate verknüpfte Biografien mit eigenen Konten schreiben. Biografien Verstorbener: nur direkte Familie; 30 Tage temporäre Prüfung nach Veröffentlichung. Nach diesen 30 Tagen bleibt eine Meldung für immer möglich.`,
  },
  faq: {
    it: `FAQ: Un account = una biografia (autobiografia O memorial). Serve un'altra? Account separato con altra email. I nuovi account sono in lista d’attesa e vedono solo la data di registrazione, mai il numero in coda. Non si scrive la biografia di un amico vivente. Note e promemoria sono privati e non si esportano. La biografia è un solo foglio. Echo sta sotto; chiudere la striscia nera nasconde la chat. Non ci sono capitoli di vita fissi né testo libero. Importa testo è sempre visibile, subito prima di Esporta, e comprende Word o PDF: i titoli diventano capitoli. Esporta comprende tutto il foglio. La revisione si blocca solo se il foglio è vuoto. Dopo la morte l'autobiografia è congelata. Ogni biografia ha un identificativo UM permanente. I memorial pubblici nei primi 30 giorni restano in catalogo con la dicitura «Nei primi 30 giorni». L'IA commerciale non si addestra sull'archivio.`,
    fr: `FAQ : Un compte = une biographie (autobiographie OU mémorial). Il en faut une autre ? Compte séparé avec un autre e-mail. Les nouveaux comptes sont sur liste d’attente et voient seulement la date d’inscription, jamais le numéro de file. Pas de biographie d’un ami vivant. Notes privées, non exportées. La biographie est une seule page. Echo est dessous ; fermer la bande noire cache la conversation. Pas de chapitres de vie fixes ni de texte libre. Importer du texte est toujours visible, juste avant Exporter, et accepte Word ou PDF : les titres deviennent des chapitres. Exporter comprend toute la page. La révision ne bloque que si la page est vide. Après le décès, l’autobiographie est figée. Chaque biographie a un identifiant UM permanent. Les mémoriaux publics dans les 30 premiers jours restent au catalogue. Pas d’entraînement IA commercial sur l’archive.`,
    de: `FAQ: Ein Konto = eine Biografie (Autobiografie ODER Gedenkbuch). Eine weitere? Separates Konto mit anderer E-Mail. Neue Konten stehen auf der Warteliste und sehen nur das Anmeldedatum, nie die Wartenummer. Keine Biografie eines lebenden Freundes. Notizen sind privat und werden nicht exportiert. Die Biografie ist eine einzige Seite. Echo steht darunter; der schwarze Streifen blendet den Chat aus. Keine festen Lebenskapitel und kein Freitextmodus. Text importieren ist immer sichtbar, direkt vor Exportieren, und nimmt Word oder PDF an: Überschriften werden Kapitel. Exportieren umfasst die ganze Seite. Die Überprüfung blockiert nur, wenn die Seite leer ist. Nach dem Tod ist die Autobiografie eingefroren. Jede Biografie hat eine dauerhafte UM-Kennung. Öffentliche Gedenkbücher in den ersten 30 Tagen bleiben im Katalog. Kein kommerzielles KI-Training auf dem Archiv.`,
  },
  editor_interface: {
    it: `L'editor non ha una barra in alto. Nel menu a sinistra: titolo (clic per rinominare), grande come i titoli dei capitoli, e nome dell'autore, poi l'elenco dei capitoli, che si riempie solo quando si segna un titolo di capitolo. In basso: stato di salvataggio, Importa testo sempre visibile, poi Esporta sempre visibile, Condividi link se la biografia non è privata, un filetto, poi Strumenti. Dentro Strumenti: visibilità (Privata, Famiglia, Pubblica), I miei dati o Chi era questa persona, note, foto, struttura del libro, revisione e pubblicazione. Su telefono e tablet lo stesso menu si apre dall'icona a sinistra nell'intestazione del sito. Admin sta solo nel menu account a destra, su ogni formato. Su schermo stretto i pulsanti di formattazione stanno nel menu Formattazione.`,
    fr: `L'éditeur n'a pas de barre du haut. Dans le menu de gauche : titre (clic pour renommer), de la même taille que les titres de chapitre, et nom de l'auteur, puis la liste des chapitres, qui se remplit seulement quand un titre de chapitre est marqué. En bas : état d'enregistrement, Importer du texte toujours visible, puis Exporter toujours visible, lien de partage si la biographie n'est pas privée, un filet, puis Outils. Dans Outils : visibilité (Privé, Famille, Public), Mes données ou Qui était cette personne, notes, photos, structure du livre, révision et publication. Sur téléphone et tablette, le même menu s'ouvre par l'icône à gauche dans l'en-tête du site. Admin est seulement dans le menu du compte à droite, à toute taille. Sur un écran étroit, les boutons de mise en forme sont dans le menu Mise en forme.`,
    de: `Der Editor hat keine obere Leiste. Im linken Menü: Titel (Klick zum Umbenennen), so groß wie die Kapiteltitel, und Autorenname, dann die Kapitelliste, die sich nur füllt, wenn ein Kapiteltitel gesetzt ist. Unten: Speicherstatus, Text importieren immer sichtbar, dann Exportieren immer sichtbar, Link teilen wenn die Biografie nicht privat ist, eine Linie, dann Werkzeuge. Darin: Sichtbarkeit (Privat, Familie, Öffentlich), Meine Angaben oder Wer diese Person war, Notizen, Fotos, Buchstruktur, Überprüfung und Veröffentlichung. Auf Smartphone und Tablet öffnet dasselbe Menü das Symbol links in der Kopfzeile. Admin ist nur im Kontomenü rechts, in jeder Größe. Auf einem schmalen Bildschirm liegen die Formatierungsschaltflächen im Menü Formatierung.`,
  },
  um_identifier: {
    it: `Ogni biografia riceve un identificativo UM permanente alla creazione. Non si sostituisce e non si rigenera. La forma scritta è del tipo UM-0000-XXXX-XXXX-XXXX: UM, trattino, anno UM con almeno quattro cifre, poi il resto. L'anno 0 UM è il 2026 gregoriano. Trattini e maiuscole non cambiano l'identificativo. Lo emette solo Biography Library (Lugano, CHE-416.014.530). Non inventarne uno. La spiegazione pubblica è su /um-identifier. L'indirizzo canonico è https://id.biographylibrary.org/ seguito dall'identificativo. Un identificativo emesso risponde per sempre. Se la biografia non è consultabile, la pagina dice che l'identificativo esiste e che il contenuto non è disponibile. L'anno UM serve alle date d'archivio (pubblicazione, crediti, colophon PDF, piè di pagina). Non è mai un anno di nascita o di morte.`,
    fr: `Chaque biographie reçoit un identifiant UM permanent à la création. Il n'est ni remplacé ni régénéré. La forme écrite ressemble à UM-0000-XXXX-XXXX-XXXX : UM, trait, année UM d'au moins quatre chiffres, puis le reste. L'an 0 UM est 2026 grégorien. Traits et casse ne changent pas l'identifiant. Seule Biography Library (Lugano, CHE-416.014.530) les émet. N'en inventez pas. L'explication publique est sur /um-identifier. L'adresse canonique est https://id.biographylibrary.org/ suivie de l'identifiant. Un identifiant émis répond pour toujours. Si la biographie n'est pas consultable, la page dit que l'identifiant existe et que le contenu n'est pas disponible. L'année UM sert aux dates d'archive (publication, crédits, colophon PDF, pied de page). Ce n'est jamais une année de naissance ou de décès.`,
    de: `Jede Biografie erhält bei der Erstellung eine dauerhafte UM-Kennung. Sie wird weder ersetzt noch neu erzeugt. Die Schreibform sieht aus wie UM-0000-XXXX-XXXX-XXXX: UM, Bindestrich, UM-Jahr mit mindestens vier Ziffern, dann der Rest. Jahr 0 UM ist 2026 gregorianisch. Bindestriche und Großschreibung ändern die Kennung nicht. Nur Biography Library (Lugano, CHE-416.014.530) gibt sie aus. Erfinden Sie keine. Die öffentliche Erklärung steht unter /um-identifier. Die kanonische Adresse ist https://id.biographylibrary.org/ gefolgt von der Kennung. Eine ausgegebene Kennung antwortet für immer. Ist die Biografie nicht einsehbar, sagt die Seite, dass die Kennung existiert und der Inhalt nicht verfügbar ist. Das UM-Jahr gilt für Archivdaten (Veröffentlichung, Impressum, PDF-Kolophon, Fußzeile). Es ist nie ein Geburts- oder Sterbejahr.`,
  },
  memorial_review_window: {
    it: `Solo i memorial. Non esiste lo stato provisional. I 30 giorni sono la data provisional_until. Finché quella data è nel futuro, un memorial pubblico resta in catalogo con la dicitura «Nei primi 30 giorni». La segnalazione è possibile durante la finestra e resta possibile per sempre dopo. La prima pubblicazione imposta la finestra a 30 giorni da published_at. Una ripubblicazione accettata imposta revised_at e una nuova finestra di 30 giorni da revised_at, senza sostituire published_at. Il primo pacchetto d'archivio di un memorial si deposita solo dopo la finestra in corso. Le autobiografie non hanno questa finestra.`,
    fr: `Mémoriaux seulement. Il n'existe pas de statut provisional. Les 30 jours sont la date provisional_until. Tant que cette date est dans le futur, un mémorial public reste au catalogue avec la mention « Dans les 30 premiers jours ». Un signalement est possible pendant la fenêtre et le reste pour toujours après. La première publication fixe la fenêtre à 30 jours après published_at. Une republication acceptée fixe revised_at et une nouvelle fenêtre de 30 jours à partir de revised_at, sans remplacer published_at. Le premier paquet d'archive d'un mémorial n'est déposé qu'après la fenêtre en cours. Les autobiographies n'ont pas cette fenêtre.`,
    de: `Nur Gedenkbücher. Es gibt keinen Status provisional. Die 30 Tage sind das Datum provisional_until. Solange dieses Datum in der Zukunft liegt, bleibt ein öffentliches Gedenkbuch im Katalog mit dem Hinweis «In den ersten 30 Tagen». Eine Meldung ist während des Fensters möglich und bleibt danach für immer möglich. Die erste Veröffentlichung setzt das Fenster auf 30 Tage nach published_at. Eine angenommene Neuveröffentlichung setzt revised_at und ein neues 30-Tage-Fenster ab revised_at, ohne published_at zu ersetzen. Das erste Archivpaket eines Gedenkbuchs wird erst nach dem laufenden Fenster hinterlegt. Autobiografien haben dieses Fenster nicht.`,
  },
};
