export interface AiSuggestion {
  id: string;
  original: string;
  suggestion: string;
  explanation: string;
  status: 'pending' | 'accepted' | 'rejected';
}

export interface AiPrompt {
  prompt: string;
  starter: string;
}

export interface AiPanelState {
  type: 'grammar' | 'prompts' | 'summary' | null;
  loading: boolean;
  suggestions: AiSuggestion[];
  prompts: AiPrompt[];
  summary: string;
  error: string | null;
}

export const INITIAL_AI_STATE: AiPanelState = {
  type: null,
  loading: false,
  suggestions: [],
  prompts: [],
  summary: '',
  error: null,
};

const FALLBACK_PROMPTS_EN: Record<string, AiPrompt[]> = {
  childhood: [
    { prompt: 'Describe your earliest memory', starter: 'My earliest memory is of...' },
    { prompt: "What's your first birthday memory?", starter: 'I remember my birthday when...' },
    { prompt: 'What was your childhood home like?', starter: 'The home I grew up in...' },
    { prompt: 'Describe an object from childhood you were attached to', starter: 'I had a special...' },
    { prompt: 'What sounds or smells instantly bring you back to childhood?', starter: 'When I smell... or hear..., I immediately remember...' },
    { prompt: 'Who was your childhood hero?', starter: 'I looked up to...' },
    { prompt: 'Who was your best friend growing up?', starter: 'My closest friend as a child...' },
    { prompt: 'What games did you play as a child?', starter: 'As a child, I loved playing...' },
    { prompt: 'What did a typical summer day look like for you?', starter: 'During summer, I would usually...' },
    { prompt: 'What made you feel safe and loved as a child?', starter: 'I felt most secure when...' },
    { prompt: 'What was your favorite family tradition?', starter: 'Every year, our family would...' },
    { prompt: 'What childhood fear did you eventually overcome?', starter: 'I used to be afraid of..., but I learned...' },
  ],
  family: [
    { prompt: 'Tell me about your parents', starter: 'My parents were...' },
    { prompt: 'What was dinnertime like in your family?', starter: 'At dinner, our family would...' },
    { prompt: 'What family traditions were most important?', starter: 'The tradition that meant the most...' },
    { prompt: 'Describe a typical family gathering', starter: 'When our family gathered together...' },
    { prompt: 'What songs, phrases, or sayings were unique to your family?', starter: 'In our family, we always said...' },
    { prompt: 'What scent reminds you of your family home?', starter: 'The smell of... always reminds me of home...' },
    { prompt: 'Describe a family member who made you laugh', starter: 'I always laughed when... would...' },
    { prompt: 'What values did your family instill in you?', starter: 'My family taught me to value...' },
    { prompt: 'Who was the most influential family member?', starter: 'The person who influenced me most...' },
    { prompt: 'What family story was told over and over?', starter: 'Our family loved to tell the story about...' },
    { prompt: 'How did your family celebrate special occasions?', starter: 'For celebrations, we would...' },
  ],
  education: [
    { prompt: 'What was your favorite subject in school?', starter: 'I was always drawn to...' },
    { prompt: 'Describe the walk or journey to school', starter: 'On my way to school, I would...' },
    { prompt: 'What did your classroom smell like?', starter: 'I remember the scent of...' },
    { prompt: 'Describe a teacher who changed your life', starter: 'There was one teacher who...' },
    { prompt: 'What was your school like?', starter: 'My school was...' },
    { prompt: 'What book or lesson opened your mind to new ideas?', starter: 'When I read... or learned about..., I realized...' },
    { prompt: 'Who did you sit with at lunch?', starter: 'At lunchtime, I would...' },
    { prompt: 'What achievement made you feel proud in school?', starter: 'I felt proud when I...' },
    { prompt: 'What did you dream of becoming?', starter: 'When I was young, I dreamed of...' },
    { prompt: 'What struggle did you face in your education?', starter: 'School was challenging when...' },
    { prompt: 'What was your most memorable school experience?', starter: 'I will never forget the time...' },
    { prompt: 'What advice would you give to a student today?', starter: 'If I could tell students today...' },
  ],
  career: [
    { prompt: 'What was your first job?', starter: 'My very first job was...' },
    { prompt: 'How did you choose your career path?', starter: 'My career began when...' },
    { prompt: 'Describe your first day at a significant job', starter: 'On my first day, I remember...' },
    { prompt: 'What sounds or smells remind you of your workplace?', starter: 'When I think of work, I remember the sound of... or smell of...' },
    { prompt: 'Who was the most memorable colleague you worked with?', starter: 'I worked with someone who...' },
    { prompt: 'What accomplishment are you most proud of?', starter: 'The achievement I am most proud of...' },
    { prompt: 'Describe a moment when you doubted your career choice', starter: 'There was a time when I questioned...' },
    { prompt: 'Who was your most influential mentor?', starter: 'I was fortunate to learn from...' },
    { prompt: 'What challenges did you face at work?', starter: 'One of the biggest challenges I faced...' },
    { prompt: 'What skill took you years to master?', starter: 'I spent years learning to...' },
    { prompt: 'How did your work change you as a person?', starter: 'Through my career, I became...' },
    { prompt: 'What would you do differently in your career?', starter: 'Looking back, I would have...' },
  ],
  'life-events': [
    { prompt: 'What moment changed the course of your life?', starter: 'Everything changed when...' },
    { prompt: 'Describe a day you will never forget', starter: 'I will always remember the day when...' },
    { prompt: 'What unexpected encounter shaped your path?', starter: 'I never expected to meet... but...' },
    { prompt: 'Describe a moment of unexpected joy', starter: 'One of my happiest surprises was...' },
    { prompt: 'What place holds the most memories for you?', starter: 'When I think of..., I remember...' },
    { prompt: 'What sound takes you back to a specific moment?', starter: 'When I hear..., I am transported to...' },
    { prompt: 'What historical event affected you personally?', starter: 'I remember when the world...' },
    { prompt: 'Describe a turning point in your life', starter: 'The moment I realized...' },
    { prompt: 'What risk did you take that paid off?', starter: 'I decided to take a chance and...' },
    { prompt: 'What adventure do you remember most vividly?', starter: 'The adventure that stands out most...' },
    { prompt: 'Describe a goodbye that changed you', starter: 'When I had to say goodbye to...' },
    { prompt: 'What moment made you feel most alive?', starter: 'I felt truly alive when...' },
  ],
  relationships: [
    { prompt: 'How did you meet your partner?', starter: 'We first met when...' },
    { prompt: 'What was your first impression of them?', starter: 'When I first saw them, I thought...' },
    { prompt: 'Describe a small gesture that meant everything', starter: 'It seemed small, but when they...' },
    { prompt: 'What song, scent, or place reminds you of someone you love?', starter: 'When I hear... or smell..., I think of...' },
    { prompt: 'What does love mean to you?', starter: 'To me, love has always meant...' },
    { prompt: 'Describe your closest friendship', starter: 'My dearest friend and I...' },
    { prompt: 'What conversation changed a relationship?', starter: 'We were talking, and suddenly...' },
    { prompt: 'Who saw the real you when others didn\'t?', starter: 'When everyone else saw..., they saw...' },
    { prompt: 'What have relationships taught you?', starter: 'Through my relationships, I learned...' },
    { prompt: 'Describe a moment of deep connection', starter: 'I felt truly connected when...' },
    { prompt: 'Who did you have to let go of?', starter: 'I had to let go of... because...' },
  ],
  challenges: [
    { prompt: 'What was the hardest thing you ever faced?', starter: 'The most difficult time in my life...' },
    { prompt: 'Describe the moment you hit rock bottom', starter: 'I reached my lowest point when...' },
    { prompt: 'How did you overcome a major obstacle?', starter: 'I found the strength to overcome...' },
    { prompt: 'Who or what helped you through your darkest time?', starter: 'When things were darkest, I was helped by...' },
    { prompt: 'What failure taught you the most?', starter: 'The failure that taught me the most...' },
    { prompt: 'What fear did you finally face?', starter: 'I was always afraid of..., but then I...' },
    { prompt: 'Describe a time you surprised yourself with your strength', starter: 'I didn\'t know I could..., but then...' },
    { prompt: 'What would you tell someone facing a similar challenge?', starter: 'If someone is going through this, I would say...' },
    { prompt: 'What advice would you give your younger self?', starter: 'If I could tell my younger self...' },
    { prompt: 'How did hardship shape who you are?', starter: 'Going through that experience made me...' },
    { prompt: 'What did you learn about yourself in crisis?', starter: 'In my most difficult moment, I discovered I...' },
  ],
  passions: [
    { prompt: 'What hobby brings you the most joy?', starter: 'Nothing makes me happier than...' },
    { prompt: 'How did you discover your passion?', starter: 'I first discovered my love for...' },
    { prompt: 'Describe the feeling when you\'re doing what you love', starter: 'When I\'m engaged in..., I feel...' },
    { prompt: 'What could you spend hours doing?', starter: 'I could spend all day...' },
    { prompt: 'What sounds, sights, or tools are part of your passion?', starter: 'When I\'m doing what I love, I see... hear... use...' },
    { prompt: 'Who shares or shared this passion with you?', starter: 'I love doing this with... because...' },
    { prompt: 'What skill did you work hardest to develop?', starter: 'The skill I worked hardest on...' },
    { prompt: 'What moment made you fall deeper in love with your passion?', starter: 'I became even more passionate when...' },
    { prompt: 'What would you create if you had unlimited time?', starter: 'If I had all the time in the world, I would...' },
    { prompt: 'What do you wish more people appreciated?', starter: 'I wish more people understood...' },
    { prompt: 'How has your passion changed over the years?', starter: 'My passion has evolved from... to...' },
  ],
  legacy: [
    { prompt: 'What do you want to be remembered for?', starter: 'I hope to be remembered as...' },
    { prompt: 'What life lesson took you longest to learn?', starter: 'It took me years to understand that...' },
    { prompt: 'What wisdom would you pass on?', starter: 'If I could share one piece of wisdom...' },
    { prompt: 'What tradition or value do you hope continues?', starter: 'I hope future generations will continue to...' },
    { prompt: 'What are you most grateful for?', starter: 'Above all, I am grateful for...' },
    { prompt: 'If you could leave one object behind, what would it be?', starter: 'I would leave behind... because it represents...' },
    { prompt: 'What mistake do you hope others won\'t repeat?', starter: 'I learned the hard way that...' },
    { prompt: 'How do you hope the world will change?', starter: 'My hope for the future is...' },
    { prompt: 'What made your life meaningful?', starter: 'My life has meaning because of...' },
    { prompt: 'What story do you want your family to know?', starter: 'I want my family to know the story of...' },
    { prompt: 'What message do you have for future generations?', starter: 'To those who come after me...' },
  ],
};

const FALLBACK_PROMPTS_IT: Record<string, AiPrompt[]> = {
  childhood: [
    { prompt: 'Descrivi il tuo primo ricordo', starter: 'Il mio primo ricordo \u00e8...' },
    { prompt: 'Qual \u00e8 il tuo primo ricordo di un compleanno?', starter: 'Ricordo il mio compleanno quando...' },
    { prompt: 'Com\'era la casa della tua infanzia?', starter: 'La casa in cui sono cresciuto...' },
    { prompt: 'Descrivi un oggetto dell\'infanzia a cui eri legato', starter: 'Avevo uno speciale...' },
    { prompt: 'Quali suoni o odori ti riportano immediatamente all\'infanzia?', starter: 'Quando sento l\'odore di... o sento..., ricordo immediatamente...' },
    { prompt: 'Chi era il tuo eroe da bambino?', starter: 'Ammiravo...' },
    { prompt: 'Chi era il tuo migliore amico da bambino?', starter: 'Il mio amico pi\u00f9 caro da bambino...' },
    { prompt: 'A quali giochi giocavi da bambino?', starter: 'Da bambino, adoravo giocare a...' },
    { prompt: 'Com\'era una tipica giornata estiva per te?', starter: 'Durante l\'estate, di solito...' },
    { prompt: 'Cosa ti faceva sentire sicuro e amato da bambino?', starter: 'Mi sentivo pi\u00f9 sicuro quando...' },
    { prompt: 'Qual era la tua tradizione familiare preferita?', starter: 'Ogni anno, la nostra famiglia...' },
    { prompt: 'Quale paura infantile hai finalmente superato?', starter: 'Avevo paura di..., ma ho imparato...' },
  ],
  family: [
    { prompt: 'Parlami dei tuoi genitori', starter: 'I miei genitori erano...' },
    { prompt: 'Com\'era l\'ora di cena nella tua famiglia?', starter: 'A cena, la nostra famiglia...' },
    { prompt: 'Quali tradizioni familiari erano pi\u00f9 importanti?', starter: 'La tradizione che significava di pi\u00f9...' },
    { prompt: 'Descrivi un tipico ritrovo familiare', starter: 'Quando la nostra famiglia si riuniva...' },
    { prompt: 'Quali canzoni, frasi o modi di dire erano unici nella tua famiglia?', starter: 'Nella nostra famiglia, dicevamo sempre...' },
    { prompt: 'Quale profumo ti ricorda la casa di famiglia?', starter: 'L\'odore di... mi ricorda sempre casa...' },
    { prompt: 'Descrivi un familiare che ti faceva ridere', starter: 'Ridevo sempre quando... faceva...' },
    { prompt: 'Quali valori ti ha trasmesso la tua famiglia?', starter: 'La mia famiglia mi ha insegnato a dare valore a...' },
    { prompt: 'Chi \u00e8 stato il familiare pi\u00f9 influente?', starter: 'La persona che mi ha influenzato di pi\u00f9...' },
    { prompt: 'Quale storia di famiglia veniva raccontata pi\u00f9 volte?', starter: 'Alla nostra famiglia piaceva raccontare la storia di...' },
    { prompt: 'Come festeggiava la tua famiglia le occasioni speciali?', starter: 'Per le celebrazioni, noi...' },
  ],
  education: [
    { prompt: 'Qual era la tua materia preferita a scuola?', starter: 'Sono sempre stato attratto da...' },
    { prompt: 'Descrivi il percorso per andare a scuola', starter: 'Andando a scuola, io...' },
    { prompt: 'Che odore aveva la tua classe?', starter: 'Ricordo il profumo di...' },
    { prompt: 'Descrivi un insegnante che ha cambiato la tua vita', starter: 'C\'era un insegnante che...' },
    { prompt: 'Com\'era la tua scuola?', starter: 'La mia scuola era...' },
    { prompt: 'Quale libro o lezione ti ha aperto la mente a nuove idee?', starter: 'Quando ho letto... o imparato di..., ho capito...' },
    { prompt: 'Con chi ti sedevi a pranzo?', starter: 'All\'ora di pranzo, io...' },
    { prompt: 'Quale risultato ti ha reso orgoglioso a scuola?', starter: 'Mi sono sentito orgoglioso quando...' },
    { prompt: 'Cosa sognavi di diventare?', starter: 'Da giovane, sognavo di...' },
    { prompt: 'Quale difficolt\u00e0 hai affrontato nella tua istruzione?', starter: 'La scuola era difficile quando...' },
    { prompt: 'Qual \u00e8 stata la tua esperienza scolastica pi\u00f9 memorabile?', starter: 'Non dimenticher\u00f2 mai la volta in cui...' },
    { prompt: 'Quale consiglio daresti a uno studente oggi?', starter: 'Se potessi dire agli studenti di oggi...' },
  ],
  career: [
    { prompt: 'Qual \u00e8 stato il tuo primo lavoro?', starter: 'Il mio primissimo lavoro era...' },
    { prompt: 'Come hai scelto la tua carriera?', starter: 'La mia carriera \u00e8 iniziata quando...' },
    { prompt: 'Descrivi il tuo primo giorno in un lavoro importante', starter: 'Il primo giorno, ricordo...' },
    { prompt: 'Quali suoni o odori ti ricordano il tuo posto di lavoro?', starter: 'Quando penso al lavoro, ricordo il suono di... o l\'odore di...' },
    { prompt: 'Chi \u00e8 stato il collega pi\u00f9 memorabile con cui hai lavorato?', starter: 'Ho lavorato con qualcuno che...' },
    { prompt: 'Di quale risultato sei pi\u00f9 orgoglioso?', starter: 'Il risultato di cui sono pi\u00f9 orgoglioso...' },
    { prompt: 'Descrivi un momento in cui hai dubitato della tua scelta professionale', starter: 'C\'\u00e8 stato un momento in cui ho messo in dubbio...' },
    { prompt: 'Chi \u00e8 stato il tuo mentore pi\u00f9 influente?', starter: 'Ho avuto la fortuna di imparare da...' },
    { prompt: 'Quali sfide hai affrontato nel lavoro?', starter: 'Una delle sfide pi\u00f9 grandi che ho affrontato...' },
    { prompt: 'Quale abilit\u00e0 ti \u00e8 costata anni per padroneggiare?', starter: 'Ho passato anni a imparare...' },
    { prompt: 'Come ti ha cambiato il tuo lavoro come persona?', starter: 'Attraverso la mia carriera, sono diventato...' },
    { prompt: 'Cosa faresti diversamente nella tua carriera?', starter: 'Guardando indietro, avrei...' },
  ],
  'life-events': [
    { prompt: 'Quale momento ha cambiato il corso della tua vita?', starter: 'Tutto \u00e8 cambiato quando...' },
    { prompt: 'Descrivi un giorno che non dimenticherai mai', starter: 'Ricorder\u00f2 sempre il giorno in cui...' },
    { prompt: 'Quale incontro inaspettato ha plasmato il tuo percorso?', starter: 'Non mi aspettavo di incontrare..., ma...' },
    { prompt: 'Descrivi un momento di gioia inaspettata', starter: 'Una delle mie sorprese pi\u00f9 belle \u00e8 stata...' },
    { prompt: 'Quale luogo custodisce pi\u00f9 ricordi per te?', starter: 'Quando penso a..., ricordo...' },
    { prompt: 'Quale suono ti riporta a un momento specifico?', starter: 'Quando sento..., sono trasportato a...' },
    { prompt: 'Quale evento storico ti ha toccato personalmente?', starter: 'Ricordo quando il mondo...' },
    { prompt: 'Descrivi un punto di svolta nella tua vita', starter: 'Il momento in cui ho capito...' },
    { prompt: 'Quale rischio hai preso che ha dato i suoi frutti?', starter: 'Ho deciso di rischiare e...' },
    { prompt: 'Quale avventura ricordi pi\u00f9 vividamente?', starter: 'L\'avventura che ricordo meglio...' },
    { prompt: 'Descrivi un addio che ti ha cambiato', starter: 'Quando ho dovuto dire addio a...' },
    { prompt: 'Quale momento ti ha fatto sentire pi\u00f9 vivo?', starter: 'Mi sono sentito veramente vivo quando...' },
  ],
  relationships: [
    { prompt: 'Come hai conosciuto il tuo partner?', starter: 'Ci siamo incontrati per la prima volta quando...' },
    { prompt: 'Qual \u00e8 stata la tua prima impressione?', starter: 'Quando l\'ho visto per la prima volta, ho pensato...' },
    { prompt: 'Descrivi un piccolo gesto che ha significato tutto', starter: 'Sembrava piccolo, ma quando ha...' },
    { prompt: 'Quale canzone, profumo o luogo ti ricorda qualcuno che ami?', starter: 'Quando sento... o sento l\'odore di..., penso a...' },
    { prompt: 'Cosa significa l\'amore per te?', starter: 'Per me, l\'amore ha sempre significato...' },
    { prompt: 'Descrivi la tua amicizia pi\u00f9 stretta', starter: 'Il mio amico pi\u00f9 caro e io...' },
    { prompt: 'Quale conversazione ha cambiato una relazione?', starter: 'Stavamo parlando, e all\'improvviso...' },
    { prompt: 'Chi ha visto il vero te quando gli altri no?', starter: 'Quando tutti gli altri vedevano..., loro vedevano...' },
    { prompt: 'Cosa ti hanno insegnato le relazioni?', starter: 'Attraverso le mie relazioni, ho imparato...' },
    { prompt: 'Descrivi un momento di profonda connessione', starter: 'Mi sono sentito veramente connesso quando...' },
    { prompt: 'Chi hai dovuto lasciare andare?', starter: 'Ho dovuto lasciare andare... perch\u00e9...' },
  ],
  challenges: [
    { prompt: 'Qual \u00e8 stata la cosa pi\u00f9 difficile che hai affrontato?', starter: 'Il periodo pi\u00f9 difficile della mia vita...' },
    { prompt: 'Descrivi il momento in cui hai toccato il fondo', starter: 'Ho raggiunto il punto pi\u00f9 basso quando...' },
    { prompt: 'Come hai superato un grande ostacolo?', starter: 'Ho trovato la forza di superare...' },
    { prompt: 'Chi o cosa ti ha aiutato nel tuo momento pi\u00f9 buio?', starter: 'Quando era pi\u00f9 buio, sono stato aiutato da...' },
    { prompt: 'Quale fallimento ti ha insegnato di pi\u00f9?', starter: 'Il fallimento che mi ha insegnato di pi\u00f9...' },
    { prompt: 'Quale paura hai finalmente affrontato?', starter: 'Avevo sempre paura di..., ma poi...' },
    { prompt: 'Descrivi un momento in cui ti sei sorpreso della tua forza', starter: 'Non sapevo di poter..., ma poi...' },
    { prompt: 'Cosa diresti a qualcuno che affronta una sfida simile?', starter: 'Se qualcuno sta attraversando questo, direi...' },
    { prompt: 'Che consiglio daresti al te stesso pi\u00f9 giovane?', starter: 'Se potessi dire al me stesso pi\u00f9 giovane...' },
    { prompt: 'Come le difficolt\u00e0 hanno plasmato chi sei?', starter: 'Attraversare quell\'esperienza mi ha reso...' },
    { prompt: 'Cosa hai imparato su te stesso nella crisi?', starter: 'Nel mio momento pi\u00f9 difficile, ho scoperto che...' },
  ],
  passions: [
    { prompt: 'Quale hobby ti d\u00e0 pi\u00f9 gioia?', starter: 'Niente mi rende pi\u00f9 felice di...' },
    { prompt: 'Come hai scoperto la tua passione?', starter: 'Ho scoperto per la prima volta il mio amore per...' },
    { prompt: 'Descrivi la sensazione quando fai ci\u00f2 che ami', starter: 'Quando mi dedico a..., mi sento...' },
    { prompt: 'Cosa potresti fare per ore?', starter: 'Potrei passare tutto il giorno a...' },
    { prompt: 'Quali suoni, immagini o strumenti fanno parte della tua passione?', starter: 'Quando faccio ci\u00f2 che amo, vedo... sento... uso...' },
    { prompt: 'Chi condivide o ha condiviso questa passione con te?', starter: 'Amo fare questo con... perch\u00e9...' },
    { prompt: 'Quale abilit\u00e0 hai lavorato di pi\u00f9 per sviluppare?', starter: 'L\'abilit\u00e0 su cui ho lavorato di pi\u00f9...' },
    { prompt: 'Quale momento ti ha fatto innamorare ancora di pi\u00f9 della tua passione?', starter: 'Sono diventato ancora pi\u00f9 appassionato quando...' },
    { prompt: 'Cosa creeresti se avessi tempo illimitato?', starter: 'Se avessi tutto il tempo del mondo, farei...' },
    { prompt: 'Cosa vorresti che pi\u00f9 persone apprezzassero?', starter: 'Vorrei che pi\u00f9 persone capissero...' },
    { prompt: 'Come \u00e8 cambiata la tua passione negli anni?', starter: 'La mia passione si \u00e8 evoluta da... a...' },
  ],
  legacy: [
    { prompt: 'Per cosa vuoi essere ricordato?', starter: 'Spero di essere ricordato come...' },
    { prompt: 'Quale lezione di vita ti \u00e8 costata pi\u00f9 tempo imparare?', starter: 'Mi ci sono voluti anni per capire che...' },
    { prompt: 'Quale saggezza trasmetteresti?', starter: 'Se potessi condividere un consiglio...' },
    { prompt: 'Quale tradizione o valore speri che continui?', starter: 'Spero che le generazioni future continueranno a...' },
    { prompt: 'Per cosa sei pi\u00f9 grato?', starter: 'Soprattutto, sono grato per...' },
    { prompt: 'Se potessi lasciare un oggetto, quale sarebbe?', starter: 'Lascerei... perch\u00e9 rappresenta...' },
    { prompt: 'Quale errore speri che altri non ripeteranno?', starter: 'Ho imparato a mie spese che...' },
    { prompt: 'Come speri che il mondo cambier\u00e0?', starter: 'La mia speranza per il futuro \u00e8...' },
    { prompt: 'Cosa ha reso significativa la tua vita?', starter: 'La mia vita ha significato grazie a...' },
    { prompt: 'Quale storia vuoi che la tua famiglia conosca?', starter: 'Voglio che la mia famiglia sappia la storia di...' },
    { prompt: 'Che messaggio hai per le generazioni future?', starter: 'A coloro che verranno dopo di me...' },
  ],
};

const FALLBACK_PROMPTS_FR: Record<string, AiPrompt[]> = {
  childhood: [
    { prompt: 'D\u00e9crivez votre premier souvenir', starter: 'Mon premier souvenir est...' },
    { prompt: 'Quel est votre premier souvenir d\'anniversaire ?', starter: 'Je me souviens de mon anniversaire quand...' },
    { prompt: 'Comment \u00e9tait la maison de votre enfance ?', starter: 'La maison o\u00f9 j\'ai grandi...' },
    { prompt: 'D\u00e9crivez un objet de l\'enfance auquel vous \u00e9tiez attach\u00e9', starter: 'J\'avais un sp\u00e9cial...' },
    { prompt: 'Quels sons ou odeurs vous ram\u00e8nent instantan\u00e9ment \u00e0 l\'enfance ?', starter: 'Quand je sens... ou j\'entends..., je me souviens imm\u00e9diatement...' },
    { prompt: 'Qui \u00e9tait votre h\u00e9ros d\'enfance ?', starter: 'J\'admirais...' },
    { prompt: 'Qui \u00e9tait votre meilleur ami d\'enfance ?', starter: 'Mon ami le plus proche quand j\'\u00e9tais enfant...' },
    { prompt: '\u00c0 quels jeux jouiez-vous enfant ?', starter: 'Quand j\'\u00e9tais enfant, j\'adorais jouer \u00e0...' },
    { prompt: '\u00c0 quoi ressemblait une journ\u00e9e d\'\u00e9t\u00e9 typique pour vous ?', starter: 'Pendant l\'\u00e9t\u00e9, je...' },
    { prompt: 'Qu\'est-ce qui vous faisait sentir en s\u00e9curit\u00e9 et aim\u00e9 enfant ?', starter: 'Je me sentais le plus en s\u00e9curit\u00e9 quand...' },
    { prompt: 'Quelle \u00e9tait votre tradition familiale pr\u00e9f\u00e9r\u00e9e ?', starter: 'Chaque ann\u00e9e, notre famille...' },
    { prompt: 'Quelle peur d\'enfance avez-vous finalement surmont\u00e9e ?', starter: 'J\'avais peur de..., mais j\'ai appris...' },
  ],
  family: [
    { prompt: 'Parlez-moi de vos parents', starter: 'Mes parents \u00e9taient...' },
    { prompt: 'Comment se passaient les repas en famille ?', starter: 'Au d\u00eener, notre famille...' },
    { prompt: 'Quelles traditions familiales \u00e9taient les plus importantes ?', starter: 'La tradition qui comptait le plus...' },
    { prompt: 'D\u00e9crivez une r\u00e9union de famille typique', starter: 'Quand notre famille se r\u00e9unissait...' },
    { prompt: 'Quelles chansons, expressions ou dictons \u00e9taient propres \u00e0 votre famille ?', starter: 'Dans notre famille, on disait toujours...' },
    { prompt: 'Quelle odeur vous rappelle votre maison familiale ?', starter: 'L\'odeur de... me rappelle toujours la maison...' },
    { prompt: 'D\u00e9crivez un membre de la famille qui vous faisait rire', starter: 'Je riais toujours quand... faisait...' },
    { prompt: 'Quelles valeurs votre famille vous a-t-elle transmises ?', starter: 'Ma famille m\'a appris \u00e0 valoriser...' },
    { prompt: 'Qui a \u00e9t\u00e9 le membre de la famille le plus influent ?', starter: 'La personne qui m\'a le plus influenc\u00e9...' },
    { prompt: 'Quelle histoire familiale \u00e9tait racont\u00e9e encore et encore ?', starter: 'Notre famille aimait raconter l\'histoire de...' },
    { prompt: 'Comment votre famille c\u00e9l\u00e9brait-elle les occasions sp\u00e9ciales ?', starter: 'Pour les c\u00e9l\u00e9brations, nous...' },
  ],
  education: [
    { prompt: 'Quelle \u00e9tait votre mati\u00e8re pr\u00e9f\u00e9r\u00e9e \u00e0 l\'\u00e9cole ?', starter: 'J\'\u00e9tais toujours attir\u00e9 par...' },
    { prompt: 'D\u00e9crivez le trajet pour aller \u00e0 l\'\u00e9cole', starter: 'En allant \u00e0 l\'\u00e9cole, je...' },
    { prompt: 'Quelle \u00e9tait l\'odeur de votre salle de classe ?', starter: 'Je me souviens de l\'odeur de...' },
    { prompt: 'D\u00e9crivez un enseignant qui a chang\u00e9 votre vie', starter: 'Il y avait un enseignant qui...' },
    { prompt: 'Comment \u00e9tait votre \u00e9cole ?', starter: 'Mon \u00e9cole \u00e9tait...' },
    { prompt: 'Quel livre ou le\u00e7on a ouvert votre esprit \u00e0 de nouvelles id\u00e9es ?', starter: 'Quand j\'ai lu... ou appris..., j\'ai r\u00e9alis\u00e9...' },
    { prompt: 'Avec qui vous asseyiez-vous au d\u00e9jeuner ?', starter: '\u00c0 l\'heure du d\u00e9jeuner, je...' },
    { prompt: 'Quelle r\u00e9alisation vous a rendu fier \u00e0 l\'\u00e9cole ?', starter: 'Je me suis senti fier quand...' },
    { prompt: 'De quoi r\u00eaviez-vous de devenir ?', starter: 'Quand j\'\u00e9tais jeune, je r\u00eavais de...' },
    { prompt: 'Quelle difficult\u00e9 avez-vous rencontr\u00e9e dans votre \u00e9ducation ?', starter: 'L\'\u00e9cole \u00e9tait difficile quand...' },
    { prompt: 'Quelle a \u00e9t\u00e9 votre exp\u00e9rience scolaire la plus m\u00e9morable ?', starter: 'Je n\'oublierai jamais la fois o\u00f9...' },
    { prompt: 'Quel conseil donneriez-vous \u00e0 un \u00e9tudiant aujourd\'hui ?', starter: 'Si je pouvais dire aux \u00e9tudiants aujourd\'hui...' },
  ],
  career: [
    { prompt: 'Quel \u00e9tait votre premier emploi ?', starter: 'Mon tout premier emploi \u00e9tait...' },
    { prompt: 'Comment avez-vous choisi votre carri\u00e8re ?', starter: 'Ma carri\u00e8re a commenc\u00e9 quand...' },
    { prompt: 'D\u00e9crivez votre premier jour dans un emploi important', starter: 'Le premier jour, je me souviens...' },
    { prompt: 'Quels sons ou odeurs vous rappellent votre lieu de travail ?', starter: 'Quand je pense au travail, je me souviens du son de... ou de l\'odeur de...' },
    { prompt: 'Qui \u00e9tait le coll\u00e8gue le plus m\u00e9morable avec qui vous avez travaill\u00e9 ?', starter: 'J\'ai travaill\u00e9 avec quelqu\'un qui...' },
    { prompt: 'De quelle r\u00e9alisation \u00eates-vous le plus fier ?', starter: 'La r\u00e9alisation dont je suis le plus fier...' },
    { prompt: 'D\u00e9crivez un moment o\u00f9 vous avez dout\u00e9 de votre choix de carri\u00e8re', starter: 'Il y a eu un moment o\u00f9 j\'ai remis en question...' },
    { prompt: 'Qui a \u00e9t\u00e9 votre mentor le plus influent ?', starter: 'J\'ai eu la chance d\'apprendre de...' },
    { prompt: 'Quels d\u00e9fis avez-vous rencontr\u00e9s au travail ?', starter: 'L\'un des plus grands d\u00e9fis que j\'ai rencontr\u00e9s...' },
    { prompt: 'Quelle comp\u00e9tence vous a pris des ann\u00e9es \u00e0 ma\u00eetriser ?', starter: 'J\'ai pass\u00e9 des ann\u00e9es \u00e0 apprendre...' },
    { prompt: 'Comment votre travail vous a-t-il chang\u00e9 en tant que personne ?', starter: '\u00c0 travers ma carri\u00e8re, je suis devenu...' },
    { prompt: 'Que feriez-vous diff\u00e9remment dans votre carri\u00e8re ?', starter: 'En regardant en arri\u00e8re, j\'aurais...' },
  ],
  'life-events': [
    { prompt: 'Quel moment a chang\u00e9 le cours de votre vie ?', starter: 'Tout a chang\u00e9 quand...' },
    { prompt: 'D\u00e9crivez un jour que vous n\'oublierez jamais', starter: 'Je me souviendrai toujours du jour o\u00f9...' },
    { prompt: 'Quelle rencontre inattendue a fa\u00e7onn\u00e9 votre chemin ?', starter: 'Je ne m\'attendais pas \u00e0 rencontrer..., mais...' },
    { prompt: 'D\u00e9crivez un moment de joie inattendue', starter: 'L\'une de mes plus belles surprises a \u00e9t\u00e9...' },
    { prompt: 'Quel lieu d\u00e9tient le plus de souvenirs pour vous ?', starter: 'Quand je pense \u00e0..., je me souviens...' },
    { prompt: 'Quel son vous ram\u00e8ne \u00e0 un moment pr\u00e9cis ?', starter: 'Quand j\'entends..., je suis transport\u00e9 \u00e0...' },
    { prompt: 'Quel \u00e9v\u00e9nement historique vous a touch\u00e9 personnellement ?', starter: 'Je me souviens quand le monde...' },
    { prompt: 'D\u00e9crivez un tournant dans votre vie', starter: 'Le moment o\u00f9 j\'ai r\u00e9alis\u00e9...' },
    { prompt: 'Quel risque avez-vous pris qui a port\u00e9 ses fruits ?', starter: 'J\'ai d\u00e9cid\u00e9 de prendre un risque et...' },
    { prompt: 'Quelle aventure vous rappel\u00e9z-vous le plus vivement ?', starter: 'L\'aventure qui me marque le plus...' },
    { prompt: 'D\u00e9crivez un adieu qui vous a chang\u00e9', starter: 'Quand j\'ai d\u00fb dire au revoir \u00e0...' },
    { prompt: 'Quel moment vous a fait vous sentir le plus vivant ?', starter: 'Je me suis senti vraiment vivant quand...' },
  ],
  relationships: [
    { prompt: 'Comment avez-vous rencontr\u00e9 votre partenaire ?', starter: 'Nous nous sommes rencontr\u00e9s pour la premi\u00e8re fois quand...' },
    { prompt: 'Quelle a \u00e9t\u00e9 votre premi\u00e8re impression ?', starter: 'Quand je les ai vus pour la premi\u00e8re fois, j\'ai pens\u00e9...' },
    { prompt: 'D\u00e9crivez un petit geste qui a tout signifi\u00e9', starter: 'Cela semblait petit, mais quand ils ont...' },
    { prompt: 'Quelle chanson, odeur ou lieu vous rappelle quelqu\'un que vous aimez ?', starter: 'Quand j\'entends... ou sens..., je pense \u00e0...' },
    { prompt: 'Que signifie l\'amour pour vous ?', starter: 'Pour moi, l\'amour a toujours signifi\u00e9...' },
    { prompt: 'D\u00e9crivez votre amiti\u00e9 la plus proche', starter: 'Mon ami le plus cher et moi...' },
    { prompt: 'Quelle conversation a chang\u00e9 une relation ?', starter: 'Nous parlions, et soudain...' },
    { prompt: 'Qui a vu le vrai vous quand les autres ne le voyaient pas ?', starter: 'Quand tout le monde voyait..., ils voyaient...' },
    { prompt: 'Qu\'est-ce que les relations vous ont appris ?', starter: '\u00c0 travers mes relations, j\'ai appris...' },
    { prompt: 'D\u00e9crivez un moment de connexion profonde', starter: 'Je me suis senti vraiment connect\u00e9 quand...' },
    { prompt: 'Qui avez-vous d\u00fb laisser partir ?', starter: 'J\'ai d\u00fb laisser partir... parce que...' },
  ],
  challenges: [
    { prompt: 'Quelle a \u00e9t\u00e9 la chose la plus difficile que vous ayez v\u00e9cue ?', starter: 'La p\u00e9riode la plus difficile de ma vie...' },
    { prompt: 'D\u00e9crivez le moment o\u00f9 vous avez touch\u00e9 le fond', starter: 'J\'ai atteint mon point le plus bas quand...' },
    { prompt: 'Comment avez-vous surmont\u00e9 un obstacle majeur ?', starter: 'J\'ai trouv\u00e9 la force de surmonter...' },
    { prompt: 'Qui ou quoi vous a aid\u00e9 dans votre moment le plus sombre ?', starter: 'Quand c\'\u00e9tait le plus sombre, j\'ai \u00e9t\u00e9 aid\u00e9 par...' },
    { prompt: 'Quel \u00e9chec vous a le plus appris ?', starter: 'L\'\u00e9chec qui m\'a le plus appris...' },
    { prompt: 'Quelle peur avez-vous finalement affront\u00e9e ?', starter: 'J\'avais toujours peur de..., mais ensuite...' },
    { prompt: 'D\u00e9crivez un moment o\u00f9 vous vous \u00eates surpris par votre force', starter: 'Je ne savais pas que je pouvais..., mais ensuite...' },
    { prompt: 'Que diriez-vous \u00e0 quelqu\'un qui fait face \u00e0 un d\u00e9fi similaire ?', starter: 'Si quelqu\'un traverse cela, je dirais...' },
    { prompt: 'Quel conseil donneriez-vous \u00e0 votre jeune vous ?', starter: 'Si je pouvais dire \u00e0 mon jeune moi...' },
    { prompt: 'Comment les difficult\u00e9s ont-elles fa\u00e7onn\u00e9 qui vous \u00eates ?', starter: 'Traverser cette exp\u00e9rience m\'a rendu...' },
    { prompt: 'Qu\'avez-vous appris sur vous-m\u00eame en crise ?', starter: 'Dans mon moment le plus difficile, j\'ai d\u00e9couvert que...' },
  ],
  passions: [
    { prompt: 'Quel passe-temps vous apporte le plus de joie ?', starter: 'Rien ne me rend plus heureux que...' },
    { prompt: 'Comment avez-vous d\u00e9couvert votre passion ?', starter: 'J\'ai d\u00e9couvert mon amour pour...' },
    { prompt: 'D\u00e9crivez le sentiment quand vous faites ce que vous aimez', starter: 'Quand je m\'engage dans..., je ressens...' },
    { prompt: 'Que pourriez-vous faire pendant des heures ?', starter: 'Je pourrais passer toute la journ\u00e9e \u00e0...' },
    { prompt: 'Quels sons, images ou outils font partie de votre passion ?', starter: 'Quand je fais ce que j\'aime, je vois... j\'entends... j\'utilise...' },
    { prompt: 'Qui partage ou a partag\u00e9 cette passion avec vous ?', starter: 'J\'aime faire cela avec... parce que...' },
    { prompt: 'Quelle comp\u00e9tence avez-vous travaill\u00e9 le plus dur pour d\u00e9velopper ?', starter: 'La comp\u00e9tence sur laquelle j\'ai le plus travaill\u00e9...' },
    { prompt: 'Quel moment vous a fait tomber encore plus amoureux de votre passion ?', starter: 'Je suis devenu encore plus passionn\u00e9 quand...' },
    { prompt: 'Que cr\u00e9eriez-vous si vous aviez un temps illimit\u00e9 ?', starter: 'Si j\'avais tout le temps du monde, je...' },
    { prompt: 'Qu\'aimeriez-vous que plus de gens appr\u00e9cient ?', starter: 'J\'aimerais que plus de gens comprennent...' },
    { prompt: 'Comment votre passion a-t-elle \u00e9volu\u00e9 au fil des ans ?', starter: 'Ma passion a \u00e9volu\u00e9 de... \u00e0...' },
  ],
  legacy: [
    { prompt: 'Pour quoi voulez-vous \u00eatre rappel\u00e9 ?', starter: 'J\'esp\u00e8re \u00eatre rappel\u00e9 comme...' },
    { prompt: 'Quelle le\u00e7on de vie vous a pris le plus de temps \u00e0 apprendre ?', starter: 'Il m\'a fallu des ann\u00e9es pour comprendre que...' },
    { prompt: 'Quelle sagesse transmettriez-vous ?', starter: 'Si je pouvais partager un conseil...' },
    { prompt: 'Quelle tradition ou valeur esp\u00e9rez-vous qui continue ?', starter: 'J\'esp\u00e8re que les g\u00e9n\u00e9rations futures continueront \u00e0...' },
    { prompt: 'De quoi \u00eates-vous le plus reconnaissant ?', starter: 'Par-dessus tout, je suis reconnaissant pour...' },
    { prompt: 'Si vous pouviez laisser un objet, lequel serait-ce ?', starter: 'Je laisserais... parce qu\'il repr\u00e9sente...' },
    { prompt: 'Quelle erreur esp\u00e9rez-vous que d\'autres ne r\u00e9p\u00e9teront pas ?', starter: 'J\'ai appris \u00e0 mes d\u00e9pens que...' },
    { prompt: 'Comment esp\u00e9rez-vous que le monde changera ?', starter: 'Mon espoir pour l\'avenir est...' },
    { prompt: 'Qu\'est-ce qui a rendu votre vie significative ?', starter: 'Ma vie a du sens gr\u00e2ce \u00e0...' },
    { prompt: 'Quelle histoire voulez-vous que votre famille connaisse ?', starter: 'Je veux que ma famille connaisse l\'histoire de...' },
    { prompt: 'Quel message avez-vous pour les g\u00e9n\u00e9rations futures ?', starter: '\u00c0 ceux qui viendront apr\u00e8s moi...' },
  ],
};

const FALLBACK_PROMPTS_DE: Record<string, AiPrompt[]> = {
  childhood: [
    { prompt: 'Beschreiben Sie Ihre fr\u00fcheste Erinnerung', starter: 'Meine fr\u00fcheste Erinnerung ist...' },
    { prompt: 'Was ist Ihre erste Geburtstagserinnerung?', starter: 'Ich erinnere mich an meinen Geburtstag, als...' },
    { prompt: 'Wie war Ihr Elternhaus?', starter: 'Das Haus, in dem ich aufgewachsen bin...' },
    { prompt: 'Beschreiben Sie einen Gegenstand aus der Kindheit, an dem Sie hingen', starter: 'Ich hatte einen besonderen...' },
    { prompt: 'Welche Ger\u00e4usche oder Ger\u00fcche bringen Sie sofort zur\u00fcck in die Kindheit?', starter: 'Wenn ich... rieche oder... h\u00f6re, erinnere ich mich sofort...' },
    { prompt: 'Wer war Ihr Kindheitsheld?', starter: 'Ich bewunderte...' },
    { prompt: 'Wer war Ihr bester Freund als Kind?', starter: 'Mein engster Freund als Kind...' },
    { prompt: 'Welche Spiele haben Sie als Kind gespielt?', starter: 'Als Kind liebte ich es zu spielen...' },
    { prompt: 'Wie sah ein typischer Sommertag f\u00fcr Sie aus?', starter: 'Im Sommer w\u00fcrde ich normalerweise...' },
    { prompt: 'Was lie\u00df Sie sich als Kind sicher und geliebt f\u00fchlen?', starter: 'Ich f\u00fchlte mich am sichersten, wenn...' },
    { prompt: 'Was war Ihre liebste Familientradition?', starter: 'Jedes Jahr hat unsere Familie...' },
    { prompt: 'Welche Kinderngst haben Sie schlie\u00dflich \u00fcberwunden?', starter: 'Ich hatte Angst vor..., aber ich lernte...' },
  ],
  family: [
    { prompt: 'Erz\u00e4hlen Sie mir von Ihren Eltern', starter: 'Meine Eltern waren...' },
    { prompt: 'Wie war die Essenszeit in Ihrer Familie?', starter: 'Beim Essen w\u00fcrde unsere Familie...' },
    { prompt: 'Welche Familientraditionen waren am wichtigsten?', starter: 'Die Tradition, die am meisten bedeutete...' },
    { prompt: 'Beschreiben Sie ein typisches Familientreffen', starter: 'Wenn unsere Familie zusammenkam...' },
    { prompt: 'Welche Lieder, Ausdr\u00fccke oder Spr\u00fcche waren einzigartig in Ihrer Familie?', starter: 'In unserer Familie sagten wir immer...' },
    { prompt: 'Welcher Duft erinnert Sie an Ihr Familienheim?', starter: 'Der Geruch von... erinnert mich immer an zu Hause...' },
    { prompt: 'Beschreiben Sie ein Familienmitglied, das Sie zum Lachen brachte', starter: 'Ich lachte immer, wenn... tat...' },
    { prompt: 'Welche Werte hat Ihnen Ihre Familie vermittelt?', starter: 'Meine Familie lehrte mich zu sch\u00e4tzen...' },
    { prompt: 'Wer war das einflussreichste Familienmitglied?', starter: 'Die Person, die mich am meisten beeinflusst hat...' },
    { prompt: 'Welche Familiengeschichte wurde immer wieder erz\u00e4hlt?', starter: 'Unsere Familie liebte es, die Geschichte von... zu erz\u00e4hlen' },
    { prompt: 'Wie feierte Ihre Familie besondere Anl\u00e4sse?', starter: 'F\u00fcr Feiern w\u00fcrden wir...' },
  ],
  education: [
    { prompt: 'Was war Ihr Lieblingsfach in der Schule?', starter: 'Ich f\u00fchlte mich immer angezogen von...' },
    { prompt: 'Beschreiben Sie den Weg zur Schule', starter: 'Auf dem Weg zur Schule w\u00fcrde ich...' },
    { prompt: 'Wie roch Ihr Klassenzimmer?', starter: 'Ich erinnere mich an den Geruch von...' },
    { prompt: 'Beschreiben Sie einen Lehrer, der Ihr Leben ver\u00e4ndert hat', starter: 'Es gab einen Lehrer, der...' },
    { prompt: 'Wie war Ihre Schule?', starter: 'Meine Schule war...' },
    { prompt: 'Welches Buch oder welche Lektion \u00f6ffnete Ihren Geist f\u00fcr neue Ideen?', starter: 'Als ich... las oder \u00fcber... lernte, erkannte ich...' },
    { prompt: 'Mit wem sa\u00dfen Sie beim Mittagessen?', starter: 'Zur Mittagszeit w\u00fcrde ich...' },
    { prompt: 'Welche Leistung machte Sie in der Schule stolz?', starter: 'Ich f\u00fchlte mich stolz, als ich...' },
    { prompt: 'Wovon haben Sie getr\u00e4umt zu werden?', starter: 'Als ich jung war, tr\u00e4umte ich davon...' },
    { prompt: 'Welche Schwierigkeit hatten Sie in Ihrer Ausbildung?', starter: 'Die Schule war schwierig, wenn...' },
    { prompt: 'Was war Ihre denkw\u00fcrdigste Schulerfahrung?', starter: 'Ich werde nie die Zeit vergessen, als...' },
    { prompt: 'Welchen Rat w\u00fcrden Sie einem Studenten heute geben?', starter: 'Wenn ich Studenten heute sagen k\u00f6nnte...' },
  ],
  career: [
    { prompt: 'Was war Ihr erster Job?', starter: 'Mein allererster Job war...' },
    { prompt: 'Wie haben Sie Ihren Berufsweg gew\u00e4hlt?', starter: 'Meine Karriere begann, als...' },
    { prompt: 'Beschreiben Sie Ihren ersten Tag in einem wichtigen Job', starter: 'Am ersten Tag erinnere ich mich...' },
    { prompt: 'Welche Ger\u00e4usche oder Ger\u00fcche erinnern Sie an Ihren Arbeitsplatz?', starter: 'Wenn ich an die Arbeit denke, erinnere ich mich an den Klang von... oder den Geruch von...' },
    { prompt: 'Wer war der denkw\u00fcrdigste Kollege, mit dem Sie gearbeitet haben?', starter: 'Ich arbeitete mit jemandem, der...' },
    { prompt: 'Auf welche Leistung sind Sie am stolzesten?', starter: 'Die Leistung, auf die ich am stolzesten bin...' },
    { prompt: 'Beschreiben Sie einen Moment, in dem Sie an Ihrer Berufswahl zweifelten', starter: 'Es gab eine Zeit, in der ich... in Frage stellte' },
    { prompt: 'Wer war Ihr einflussreichster Mentor?', starter: 'Ich hatte das Gl\u00fcck, von ... zu lernen...' },
    { prompt: 'Welche Herausforderungen hatten Sie bei der Arbeit?', starter: 'Eine der gr\u00f6\u00dften Herausforderungen...' },
    { prompt: 'Welche F\u00e4higkeit brauchte Jahre, um sie zu meistern?', starter: 'Ich verbrachte Jahre damit zu lernen...' },
    { prompt: 'Wie hat Ihre Arbeit Sie als Person ver\u00e4ndert?', starter: 'Durch meine Karriere wurde ich...' },
    { prompt: 'Was w\u00fcrden Sie in Ihrer Karriere anders machen?', starter: 'R\u00fcckblickend h\u00e4tte ich...' },
  ],
  'life-events': [
    { prompt: 'Welcher Moment hat den Verlauf Ihres Lebens ver\u00e4ndert?', starter: 'Alles \u00e4nderte sich, als...' },
    { prompt: 'Beschreiben Sie einen Tag, den Sie nie vergessen werden', starter: 'Ich werde mich immer an den Tag erinnern, als...' },
    { prompt: 'Welche unerwartete Begegnung formte Ihren Weg?', starter: 'Ich erwartete nicht, ... zu treffen, aber...' },
    { prompt: 'Beschreiben Sie einen Moment unerwarteter Freude', starter: 'Eine meiner sch\u00f6nsten \u00dcberraschungen war...' },
    { prompt: 'Welcher Ort h\u00e4lt die meisten Erinnerungen f\u00fcr Sie?', starter: 'Wenn ich an... denke, erinnere ich mich...' },
    { prompt: 'Welcher Klang bringt Sie zu einem bestimmten Moment zur\u00fcck?', starter: 'Wenn ich... h\u00f6re, werde ich zu... transportiert' },
    { prompt: 'Welches historische Ereignis hat Sie pers\u00f6nlich betroffen?', starter: 'Ich erinnere mich, als die Welt...' },
    { prompt: 'Beschreiben Sie einen Wendepunkt in Ihrem Leben', starter: 'Der Moment, als ich erkannte...' },
    { prompt: 'Welches Risiko haben Sie eingegangen, das sich ausgezahlt hat?', starter: 'Ich beschloss, ein Risiko einzugehen und...' },
    { prompt: 'An welches Abenteuer erinnern Sie sich am lebhaftesten?', starter: 'Das Abenteuer, das am meisten hervorsticht...' },
    { prompt: 'Beschreiben Sie einen Abschied, der Sie ver\u00e4ndert hat', starter: 'Als ich mich von... verabschieden musste' },
    { prompt: 'Welcher Moment lie\u00df Sie sich am lebendigsten f\u00fchlen?', starter: 'Ich f\u00fchlte mich wirklich lebendig, als...' },
  ],
  relationships: [
    { prompt: 'Wie haben Sie Ihren Partner kennengelernt?', starter: 'Wir haben uns zum ersten Mal getroffen, als...' },
    { prompt: 'Was war Ihr erster Eindruck von ihnen?', starter: 'Als ich sie zum ersten Mal sah, dachte ich...' },
    { prompt: 'Beschreiben Sie eine kleine Geste, die alles bedeutete', starter: 'Es schien klein, aber als sie...' },
    { prompt: 'Welches Lied, welcher Duft oder Ort erinnert Sie an jemanden, den Sie lieben?', starter: 'Wenn ich... h\u00f6re oder... rieche, denke ich an...' },
    { prompt: 'Was bedeutet Liebe f\u00fcr Sie?', starter: 'F\u00fcr mich hat Liebe immer bedeutet...' },
    { prompt: 'Beschreiben Sie Ihre engste Freundschaft', starter: 'Mein liebster Freund und ich...' },
    { prompt: 'Welches Gespr\u00e4ch hat eine Beziehung ver\u00e4ndert?', starter: 'Wir sprachen, und pl\u00f6tzlich...' },
    { prompt: 'Wer sah das wahre Sie, wenn andere es nicht taten?', starter: 'Als alle anderen... sahen, sahen sie...' },
    { prompt: 'Was haben Beziehungen Ihnen beigebracht?', starter: 'Durch meine Beziehungen habe ich gelernt...' },
    { prompt: 'Beschreiben Sie einen Moment tiefer Verbundenheit', starter: 'Ich f\u00fchlte mich wirklich verbunden, als...' },
    { prompt: 'Wen mussten Sie loslassen?', starter: 'Ich musste... loslassen, weil...' },
  ],
  challenges: [
    { prompt: 'Was war das Schwerste, dem Sie je begegnet sind?', starter: 'Die schwierigste Zeit meines Lebens...' },
    { prompt: 'Beschreiben Sie den Moment, als Sie den Tiefpunkt erreichten', starter: 'Ich erreichte meinen tiefsten Punkt, als...' },
    { prompt: 'Wie haben Sie ein gro\u00dfes Hindernis \u00fcberwunden?', starter: 'Ich fand die Kraft zu \u00fcberwinden...' },
    { prompt: 'Wer oder was half Ihnen in Ihrer dunkelsten Zeit?', starter: 'Als es am dunkelsten war, wurde mir geholfen von...' },
    { prompt: 'Welches Scheitern hat Ihnen am meisten beigebracht?', starter: 'Das Scheitern, das mich am meisten gelehrt hat...' },
    { prompt: 'Welcher Angst haben Sie sich schlie\u00dflich gestellt?', starter: 'Ich hatte immer Angst vor..., aber dann...' },
    { prompt: 'Beschreiben Sie einen Moment, in dem Sie sich mit Ihrer St\u00e4rke \u00fcberraschten', starter: 'Ich wusste nicht, dass ich... konnte, aber dann...' },
    { prompt: 'Was w\u00fcrden Sie jemandem sagen, der einer \u00e4hnlichen Herausforderung gegen\u00fcbersteht?', starter: 'Wenn jemand das durchmacht, w\u00fcrde ich sagen...' },
    { prompt: 'Welchen Rat w\u00fcrden Sie Ihrem j\u00fcngeren Ich geben?', starter: 'Wenn ich meinem j\u00fcngeren Ich sagen k\u00f6nnte...' },
    { prompt: 'Wie haben Schwierigkeiten gepr\u00e4gt, wer Sie sind?', starter: 'Diese Erfahrung durchzumachen hat mich...' },
    { prompt: 'Was haben Sie in der Krise \u00fcber sich selbst gelernt?', starter: 'In meinem schwierigsten Moment entdeckte ich, dass ich...' },
  ],
  passions: [
    { prompt: 'Welches Hobby bringt Ihnen die meiste Freude?', starter: 'Nichts macht mich gl\u00fccklicher als...' },
    { prompt: 'Wie haben Sie Ihre Leidenschaft entdeckt?', starter: 'Ich entdeckte zum ersten Mal meine Liebe zu...' },
    { prompt: 'Beschreiben Sie das Gef\u00fchl, wenn Sie tun, was Sie lieben', starter: 'Wenn ich mich mit... besch\u00e4ftige, f\u00fchle ich...' },
    { prompt: 'Was k\u00f6nnten Sie stundenlang tun?', starter: 'Ich k\u00f6nnte den ganzen Tag...' },
    { prompt: 'Welche Ger\u00e4usche, Bilder oder Werkzeuge sind Teil Ihrer Leidenschaft?', starter: 'Wenn ich tue, was ich liebe, sehe ich... h\u00f6re ich... benutze ich...' },
    { prompt: 'Wer teilt oder teilte diese Leidenschaft mit Ihnen?', starter: 'Ich liebe es, das mit... zu tun, weil...' },
    { prompt: 'Welche F\u00e4higkeit haben Sie am h\u00e4rtesten erarbeitet?', starter: 'Die F\u00e4higkeit, an der ich am h\u00e4rtesten gearbeitet habe...' },
    { prompt: 'Welcher Moment lie\u00df Sie sich noch mehr in Ihre Leidenschaft verlieben?', starter: 'Ich wurde noch leidenschaftlicher, als...' },
    { prompt: 'Was w\u00fcrden Sie schaffen, wenn Sie unbegrenzt Zeit h\u00e4tten?', starter: 'Wenn ich alle Zeit der Welt h\u00e4tte, w\u00fcrde ich...' },
    { prompt: 'Was w\u00fcnschen Sie sich, dass mehr Menschen sch\u00e4tzen?', starter: 'Ich w\u00fcnschte, mehr Menschen w\u00fcrden verstehen...' },
    { prompt: 'Wie hat sich Ihre Leidenschaft im Laufe der Jahre ver\u00e4ndert?', starter: 'Meine Leidenschaft hat sich entwickelt von... zu...' },
  ],
  legacy: [
    { prompt: 'Wof\u00fcr m\u00f6chten Sie in Erinnerung bleiben?', starter: 'Ich hoffe, in Erinnerung zu bleiben als...' },
    { prompt: 'Welche Lebenslektion hat am l\u00e4ngsten gedauert zu lernen?', starter: 'Es hat Jahre gedauert zu verstehen, dass...' },
    { prompt: 'Welche Weisheit w\u00fcrden Sie weitergeben?', starter: 'Wenn ich eine Weisheit teilen k\u00f6nnte...' },
    { prompt: 'Welche Tradition oder welcher Wert soll Ihrer Meinung nach fortgesetzt werden?', starter: 'Ich hoffe, dass zuk\u00fcnftige Generationen weiterhin...' },
    { prompt: 'Wof\u00fcr sind Sie am dankbarsten?', starter: 'Vor allem bin ich dankbar f\u00fcr...' },
    { prompt: 'Wenn Sie einen Gegenstand hinterlassen k\u00f6nnten, welcher w\u00e4re es?', starter: 'Ich w\u00fcrde... hinterlassen, weil es... repr\u00e4sentiert' },
    { prompt: 'Welchen Fehler hoffen Sie, dass andere nicht wiederholen?', starter: 'Ich habe auf die harte Tour gelernt, dass...' },
    { prompt: 'Wie hoffen Sie, dass sich die Welt ver\u00e4ndern wird?', starter: 'Meine Hoffnung f\u00fcr die Zukunft ist...' },
    { prompt: 'Was hat Ihr Leben bedeutsam gemacht?', starter: 'Mein Leben hat Bedeutung durch...' },
    { prompt: 'Welche Geschichte m\u00f6chten Sie, dass Ihre Familie kennt?', starter: 'Ich m\u00f6chte, dass meine Familie die Geschichte von... kennt' },
    { prompt: 'Welche Botschaft haben Sie f\u00fcr zuk\u00fcnftige Generationen?', starter: 'An diejenigen, die nach mir kommen...' },
  ],
};

const ALL_FALLBACK_PROMPTS: Record<string, Record<string, AiPrompt[]>> = {
  en: FALLBACK_PROMPTS_EN,
  it: FALLBACK_PROMPTS_IT,
  fr: FALLBACK_PROMPTS_FR,
  de: FALLBACK_PROMPTS_DE,
};

export function getFallbackPrompts(language: string = 'en'): Record<string, AiPrompt[]> {
  return ALL_FALLBACK_PROMPTS[language] || ALL_FALLBACK_PROMPTS['en'];
}

export const FALLBACK_PROMPTS = FALLBACK_PROMPTS_EN;
